### ISSUE TITLE
Change name on NPM

### ISSUE THREAD

**Issue by roll** [frictionlessdata/dpm-js#58]
# Overview

Now it's `datapackage` clashing with actual `datapackage-js`.

Based on discussion - https://github.com/frictionlessdata/datapackage-js/issues/3

**Comment by rgrp** [comment]
@roll i think i'd actually vote for dpmjs rather than datapackagemanager but I'm not too bothered. Any thoughts from others?

**Comment by roll** [comment]
@rufuspollock 
I'm ready to start work on it:
- please add me to `datapackage` collaborators on npm - https://www.npmjs.com/~roll
- also what's our final decision on new name for dpm? (cc@pwalsh). I would day if `dpm-py` will be released as `dpmpy` (based on current setup.py) we should use `dpmjs`. Or may be change both to use hyphen (dpm-js, dpm-py) but it seems reasonable to sync on consistent PyPi/NPM naming.
- npm allow us to introduce breaking changes as `v0.8.0` because all installations use `^0.7.8` syntax by default for dependencies so it will not automatically jump to next minor version (because it's under v1)
- based on it I suppose note about breaking changes/renaming on top of README will be enough

**Comment by rufuspollock** [comment]
@roll i've added you.

Re naming the package let's distinguish that from the cli tool. On command line you don't want a `-` so i'd guess it is dpmpy or dpmjs (it one of them does not get to own dpm - maybe we want one of them to own that but is for later).

So for library: on pypi / npm i'd go for plain `dpm` (but we can't have that on npm ...). Second best is datapackage-manager or dpmjs - you choose.

**Comment by roll** [comment]
@rufuspollock 
I mean you use here - https://github.com/frictionlessdata/dpm-py/blob/master/setup.py#L38 - dpmpy for PyPi name so I think dpmjs on NPM will be the best choice.

@pwalsh you was voting for datapackagemanager. Does dpmpy and dpmjs in package indexes make sense for you?
